version: "3.8"
services:
  backend:
    build: ./server
    container_name: talk2task-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: talk2task-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: talk2task-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talk2task
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
